* Question 2;
options ls=78;
title "STAT 505 - Final Exam";
data wolves;
infile 'X:\STAT 505\wolves.dat' delimiter='09'x;
input id location $ x1 x2 x3 x4 x5 x6 x7 x8 x9;
run;
proc sort data=wolves;
by id;
run;
* Ward's Methods with 2 clusters;
proc cluster data=wolves method=ward outtree=clust1;
var x1 x2 x3 x4 x5 x6 x7 x8 x9;
id id;
run;
proc tree horizontal nclusters=2 out=clust2;
id id;
run;
proc sort;
by id;
run;
data combine;
merge wolves clust2;
by id;
run;
proc glm;
class cluster;
model x1 x2 x3 x4 x5 x6 x7 x8 x9 = cluster;
means cluster;
run; quit;
* Question 4;
options ls=78;
title "STAT 505 - Final Exam";
data wolves;
infile 'X:\STAT 505\wolves.dat' delimiter='09'x;
input id location $ x1 x2 x3 x4 x5 x6 x7 x8 x9;
run;
proc princomp data=wolves;
  var x1 x2 x3 x4 x5 x6 x7 x8 x9;
  run; quit;
