options ls=78;
data cereal;
infile 'X:\STAT 505\cereal.dat';
  input name man cal pro fat sod fib carb sugar pot;
  ident=_n_; *creates an id number for each site;
  run;
  proc sort data=cereal;
  by ident;
  run;
* ##############################################################################;
  * Single Linkage with 2 clusters;
proc cluster data=cereal method=single outtree=clust1;
  var cal pro fat sod fib carb sugar pot;
id ident;
run;
proc tree data=clust1 nclusters=2 out=clust2;
  id ident;
  run;
proc sort data=clust2;
  by ident;
  run;
data combine1; *combines original observations with their cluster assignments;
  merge cereal clust2;
  by ident;
  run;
proc glm data=combine1;
  class cluster;
  model cal pro fat sod fib carb sugar pot = cluster;
  means cluster;
  run; quit;
* k-means procedure with 2 clusters;
proc fastclus data=cereal maxclusters=2 maxiter=100 out=clust3 replace=random;
*proc fastclus data=wood maxclusters=4 maxiter=100 out=clust radius=20;
  var cal pro fat sod fib carb sugar pot;
  id ident;
  run;
proc glm data=clust3;
  class cluster;
  model cal pro fat sod fib carb sugar pot = cluster;
  means cluster;
  run; quit;
* ###############################################################################;
  * Single Linkage with 3 clusters;
proc cluster data=cereal method=single outtree=clust4;
  var cal pro fat sod fib carb sugar pot;
id ident;
run;
proc tree data=clust4 nclusters=3 out=clust5;
  id ident;
  run;
proc sort data=clust5;
  by ident;
  run;
data combine2; *combines original observations with their cluster assignments;
  merge cereal clust5;
  by ident;
  run;
proc glm data=combine2;
  class cluster;
  model cal pro fat sod fib carb sugar pot = cluster;
  means cluster;
  run; quit;
* k-means procedure with 3 clusters;
proc fastclus data=cereal maxclusters=3 maxiter=100 out=clust6 replace=random;
*proc fastclus data=wood maxclusters=4 maxiter=100 out=clust radius=20;
 var cal pro fat sod fib carb sugar pot;
  id ident;
  run;
proc glm data=clust6;
  class cluster;
  model cal pro fat sod fib carb sugar pot = cluster;
  means cluster;
  run; quit;
* ################################################################################;
  * Single Linkage with 4 clusters;
proc cluster data=cereal method=single outtree=clust7;
  var cal pro fat sod fib carb sugar pot;
id ident;
run;
proc tree data=clust7 nclusters=4 out=clust8;
  id ident;
  run;
proc sort data=clust8;
  by ident;
  run;
data combine3; *combines original observations with their cluster assignments;
  merge cereal clust8;
  by ident;
  run;
proc glm data=combine3;
  class cluster;
  model cal pro fat sod fib carb sugar pot = cluster;
  means cluster;
  run; quit;
* k-means procedure with 4 clusters;
proc fastclus data=cereal maxclusters=4 maxiter=100 out=clust9 replace=random;
*proc fastclus data=wood maxclusters=4 maxiter=100 out=clust radius=20;
 var cal pro fat sod fib carb sugar pot;
  id ident;
  run;
proc glm data=clust9;
  class cluster;
  model cal pro fat sod fib carb sugar pot = cluster;
  means cluster;
  run; quit;
